import type { FoodGroup } from '@gart/shared';

/**
 * The global food library.
 *
 * PROVENANCE, which is the whole point of the `source` column:
 *
 * - `FDC` — values taken from USDA FoodData Central, which is published under
 *   CC0 1.0 (public domain). No permission is required, including for
 *   commercial use; USDA asks to be cited, which is what the source string on
 *   every one of these rows does. Full citation:
 *
 *     U.S. Department of Agriculture, Agricultural Research Service,
 *     FoodData Central. https://fdc.nal.usda.gov/
 *
 * - `OWN` — Ukrainian foods and dishes with no FoodData Central equivalent
 *   (ряжанка, сирники, борщ, кров'янка and the rest). These are OUR OWN
 *   ESTIMATES and say so, rather than borrowing an authority they do not have.
 *   They are honest working figures, not laboratory analyses.
 *
 * Open Food Facts is deliberately NOT used and must not be used later. It is
 * ODbL: attribution AND share-alike, and specifically, a database combining OFF
 * data must itself be released as open data. That is viral, and it would take
 * this catalogue with it.
 *
 * Generic foods only, never branded — a branded product is a label that changes
 * without telling us, and it belongs to the trainer who adds it.
 */

/**
 * A zero here is MEASURED, not missing.
 *
 * FoodData Central reports fibre and sugars as 0 for flesh, egg, fat and
 * unsweetened drink — those are analytical results. Recording them as null
 * would say «nobody looked», and because `sumNutrients` propagates an unknown
 * on purpose, one glass of milk on a plate would make a whole day's fibre
 * total unknown. Only genuinely unmeasured values stay absent.
 */
const FDC = 'USDA FoodData Central (CC0)';
const OWN = 'Оцінка Gart';

export interface GlobalFood {
  name: string;
  group: FoodGroup;
  kcal: string;
  protein: string;
  fat: string;
  carbs: string;
  fibre?: string;
  sugars?: string;
  saturatedFat?: string;
  salt?: string;
  source: string;
  /** Named measures a person actually uses, with what they weigh. */
  portions?: { label: string; grams: string }[];
}

export const GLOBAL_FOODS: GlobalFood[] = [
  // ── Крупи та каші ───────────────────────────────────────────────────────
  {
    name: 'Гречка, крупа суха',
    group: 'GRAINS',
    kcal: '343.00',
    protein: '13.25',
    fat: '3.40',
    carbs: '71.50',
    fibre: '10.00',
    saturatedFat: '0.74',
    source: FDC,
    portions: [
      { label: 'склянка', grams: '200.00' },
      { label: 'столова ложка', grams: '25.00' },
    ],
  },
  {
    name: 'Гречка варена',
    group: 'GRAINS',
    kcal: '92.00',
    protein: '3.38',
    fat: '0.62',
    carbs: '19.94',
    fibre: '2.70',
    sugars: '0.90',
    saturatedFat: '0.14',
    source: FDC,
    portions: [{ label: 'порція', grams: '180.00' }],
  },
  {
    name: 'Рис білий, сухий',
    group: 'GRAINS',
    kcal: '365.00',
    protein: '7.13',
    fat: '0.66',
    carbs: '79.95',
    fibre: '1.30',
    sugars: '0.12',
    saturatedFat: '0.18',
    source: FDC,
    portions: [{ label: 'склянка', grams: '185.00' }],
  },
  {
    name: 'Рис білий варений',
    group: 'GRAINS',
    kcal: '130.00',
    protein: '2.69',
    fat: '0.28',
    carbs: '28.17',
    fibre: '0.40',
    sugars: '0.05',
    saturatedFat: '0.08',
    source: FDC,
    portions: [{ label: 'порція', grams: '180.00' }],
  },
  {
    name: 'Вівсяні пластівці',
    group: 'GRAINS',
    kcal: '389.00',
    protein: '16.89',
    fat: '6.90',
    carbs: '66.27',
    fibre: '10.60',
    saturatedFat: '1.22',
    source: FDC,
    portions: [
      { label: 'склянка', grams: '90.00' },
      { label: 'столова ложка', grams: '12.00' },
    ],
  },
  {
    name: 'Пшоно, крупа суха',
    group: 'GRAINS',
    kcal: '378.00',
    protein: '11.02',
    fat: '4.22',
    carbs: '72.85',
    fibre: '8.50',
    saturatedFat: '0.72',
    source: FDC,
  },
  {
    name: 'Перлова крупа',
    group: 'GRAINS',
    kcal: '352.00',
    protein: '9.91',
    fat: '1.16',
    carbs: '77.72',
    fibre: '15.60',
    sugars: '0.80',
    saturatedFat: '0.24',
    source: FDC,
  },
  {
    name: 'Манна крупа',
    group: 'GRAINS',
    kcal: '360.00',
    protein: '12.68',
    fat: '1.05',
    carbs: '72.83',
    fibre: '3.90',
    saturatedFat: '0.15',
    source: FDC,
  },
  {
    // Whole-grain cornmeal throughout, from ONE FoodData Central row — the
    // earlier figures mixed a degermed entry's energy with a whole-grain
    // entry's fat and fibre.
    name: 'Кукурудзяна крупа (цільнозернова)',
    group: 'GRAINS',
    kcal: '362.00',
    protein: '8.12',
    fat: '3.59',
    carbs: '76.89',
    fibre: '7.30',
    sugars: '0.64',
    saturatedFat: '0.50',
    salt: '0.01',
    source: FDC,
  },
  {
    name: 'Макарони варені',
    group: 'GRAINS',
    kcal: '158.00',
    protein: '5.80',
    fat: '0.93',
    carbs: '30.86',
    fibre: '1.80',
    sugars: '0.56',
    saturatedFat: '0.18',
    source: FDC,
    portions: [{ label: 'порція', grams: '200.00' }],
  },

  // ── М'ясо ───────────────────────────────────────────────────────────────
  {
    name: 'Куряча грудка без шкіри, сира',
    group: 'MEAT',
    kcal: '120.00',
    protein: '22.50',
    fat: '2.62',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '0.68',
    salt: '0.11',
    source: FDC,
    portions: [{ label: 'філе', grams: '180.00' }],
  },
  {
    name: 'Куряче стегно без шкіри, сире',
    group: 'MEAT',
    kcal: '121.00',
    protein: '19.70',
    fat: '4.10',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '1.09',
    salt: '0.21',
    source: FDC,
  },
  {
    name: 'Індиче філе, сире',
    group: 'MEAT',
    kcal: '114.00',
    protein: '23.66',
    fat: '1.27',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '0.38',
    salt: '0.14',
    source: FDC,
  },
  {
    name: 'Свинина, вирізка, сира',
    group: 'MEAT',
    kcal: '143.00',
    protein: '20.95',
    fat: '5.94',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '2.04',
    salt: '0.13',
    source: FDC,
  },
  {
    name: 'Яловичина пісна, сира',
    group: 'MEAT',
    kcal: '143.00',
    protein: '21.20',
    fat: '5.70',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '2.20',
    salt: '0.14',
    source: FDC,
  },
  {
    name: 'Печінка куряча, сира',
    group: 'MEAT',
    kcal: '116.00',
    protein: '16.92',
    fat: '4.83',
    carbs: '0.73',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '1.56',
    salt: '0.18',
    source: FDC,
  },
  {
    // 902 kcal at exactly 100 g fat and zero protein is RENDERED lard, which is
    // definitionally all lipid — so it is named as such. Salo as eaten is
    // salt-cured fatback, and is its own row below.
    name: 'Смалець (топлений свинячий жир)',
    group: 'FATS_OILS',
    kcal: '902.00',
    protein: '0.00',
    fat: '100.00',
    carbs: '0.00',
    fibre: '0.00',
    sugars: '0.00',
    saturatedFat: '39.20',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'столова ложка', grams: '13.00' }],
  },
  {
    name: 'Сало солоне',
    group: 'MEAT',
    kcal: '780.00',
    protein: '2.40',
    fat: '85.00',
    carbs: '0.00',
    fibre: '0.00',
    sugars: '0.00',
    saturatedFat: '32.00',
    salt: '2.00',
    source: OWN,
    portions: [{ label: 'скибка', grams: '15.00' }],
  },
  {
    // FoodData Central does carry blood sausage, and these are its figures — so
    // this is FDC-sourced, not ours. Claiming otherwise would misattribute
    // provenance in the one column that exists to record it.
    name: "Кров'янка",
    group: 'MEAT',
    kcal: '379.00',
    protein: '14.60',
    fat: '34.50',
    carbs: '1.29',
    fibre: '0.00',
    sugars: '0.00',
    saturatedFat: '13.40',
    salt: '1.70',
    source: FDC,
  },

  // ── Риба та морепродукти ────────────────────────────────────────────────
  {
    name: 'Оселедець атлантичний, сирий',
    group: 'FISH',
    kcal: '158.00',
    protein: '17.96',
    fat: '9.04',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '2.04',
    salt: '0.23',
    source: FDC,
  },
  {
    name: 'Лосось атлантичний, сирий',
    group: 'FISH',
    kcal: '208.00',
    protein: '20.42',
    fat: '13.42',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '3.05',
    salt: '0.15',
    source: FDC,
    portions: [{ label: 'стейк', grams: '150.00' }],
  },
  {
    name: 'Скумбрія, сира',
    group: 'FISH',
    kcal: '205.00',
    protein: '18.60',
    fat: '13.89',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '3.26',
    salt: '0.22',
    source: FDC,
  },
  {
    name: 'Тріска, сира',
    group: 'FISH',
    kcal: '82.00',
    protein: '17.81',
    fat: '0.67',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '0.13',
    salt: '0.13',
    source: FDC,
  },
  {
    name: 'Тунець консервований у власному соку',
    group: 'FISH',
    kcal: '116.00',
    protein: '25.51',
    fat: '0.82',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '0.23',
    salt: '0.83',
    source: FDC,
    // Drained, because the nutrients are the drained basis. A 160 g can yields
    // roughly this much fish; labelling the gross weight overstated protein by
    // about a third.
    portions: [{ label: 'банка (зціджена)', grams: '110.00' }],
  },

  // ── Молочні продукти ────────────────────────────────────────────────────
  {
    name: 'Молоко 3,2%',
    group: 'DAIRY',
    // FoodData Central reports 4.8 g carbohydrate and 5.05 g sugars for whole
    // milk — the two come from different analytical methods and cannot both be
    // right. Lactose is essentially all of milk's carbohydrate, so sugars are
    // taken as equal to it rather than exceeding it.
    kcal: '61.00',
    protein: '3.15',
    fat: '3.25',
    carbs: '4.80',
    fibre: '0.00',
    sugars: '4.80',
    saturatedFat: '1.87',
    salt: '0.10',
    source: FDC,
    portions: [{ label: 'склянка', grams: '250.00' }],
  },
  {
    name: 'Йогурт натуральний без цукру',
    group: 'DAIRY',
    kcal: '61.00',
    protein: '3.47',
    fat: '3.25',
    carbs: '4.66',
    fibre: '0.00',
    sugars: '4.66',
    saturatedFat: '2.10',
    salt: '0.11',
    source: FDC,
    portions: [{ label: 'баночка', grams: '150.00' }],
  },
  {
    name: 'Кефір 2,5%',
    group: 'DAIRY',
    kcal: '53.00',
    protein: '3.00',
    fat: '2.50',
    carbs: '4.00',
    fibre: '0.00',
    sugars: '4.00',
    saturatedFat: '1.60',
    salt: '0.10',
    source: OWN,
    portions: [{ label: 'склянка', grams: '250.00' }],
  },
  {
    name: 'Ряжанка 4%',
    group: 'DAIRY',
    kcal: '67.00',
    protein: '2.90',
    fat: '4.00',
    carbs: '4.20',
    fibre: '0.00',
    sugars: '4.20',
    saturatedFat: '2.50',
    salt: '0.10',
    source: OWN,
    portions: [{ label: 'склянка', grams: '250.00' }],
  },
  {
    name: 'Сметана 20%',
    group: 'DAIRY',
    kcal: '206.00',
    protein: '2.80',
    fat: '20.00',
    carbs: '3.40',
    fibre: '0.00',
    sugars: '3.40',
    saturatedFat: '12.50',
    salt: '0.08',
    source: OWN,
    portions: [{ label: 'столова ложка', grams: '25.00' }],
  },
  {
    name: 'Сир кисломолочний 5%',
    group: 'DAIRY',
    kcal: '121.00',
    protein: '17.00',
    fat: '5.00',
    carbs: '1.80',
    fibre: '0.00',
    sugars: '1.80',
    saturatedFat: '3.20',
    salt: '0.10',
    source: OWN,
    portions: [{ label: 'порція', grams: '200.00' }],
  },
  {
    name: 'Твердий сир (типу гауда)',
    group: 'DAIRY',
    kcal: '356.00',
    protein: '24.94',
    fat: '27.44',
    carbs: '2.22',
    fibre: '0.00',
    sugars: '2.22',
    saturatedFat: '17.61',
    salt: '2.00',
    source: FDC,
    portions: [{ label: 'скибка', grams: '20.00' }],
  },
  {
    name: 'Вершкове масло 82%',
    group: 'DAIRY',
    kcal: '717.00',
    protein: '0.85',
    fat: '81.11',
    carbs: '0.06',
    fibre: '0.00',
    sugars: '0.06',
    saturatedFat: '51.37',
    salt: '0.02',
    source: FDC,
    portions: [{ label: 'чайна ложка', grams: '5.00' }],
  },

  // ── Яйця ────────────────────────────────────────────────────────────────
  {
    name: 'Яйце куряче, сире',
    group: 'EGGS',
    kcal: '143.00',
    protein: '12.56',
    fat: '9.51',
    carbs: '0.72',
    fibre: '0.00',
    sugars: '0.37',
    saturatedFat: '3.13',
    salt: '0.36',
    source: FDC,
    portions: [
      { label: 'яйце середнє', grams: '55.00' },
      { label: 'яйце велике', grams: '63.00' },
    ],
  },
  {
    name: 'Яєчний білок',
    group: 'EGGS',
    kcal: '52.00',
    protein: '10.90',
    fat: '0.17',
    carbs: '0.73',
    fibre: '0.00',
    sugars: '0.71',
    saturatedFat: '0.00',
    salt: '0.42',
    source: FDC,
    portions: [{ label: 'білок одного яйця', grams: '33.00' }],
  },
  {
    name: 'Яєчний жовток',
    group: 'EGGS',
    kcal: '322.00',
    protein: '15.86',
    fat: '26.54',
    carbs: '3.59',
    fibre: '0.00',
    sugars: '0.56',
    saturatedFat: '9.55',
    salt: '0.12',
    source: FDC,
    portions: [{ label: 'жовток одного яйця', grams: '17.00' }],
  },

  // ── Овочі ───────────────────────────────────────────────────────────────
  {
    name: 'Картопля варена',
    group: 'VEGETABLES',
    kcal: '87.00',
    protein: '1.87',
    fat: '0.10',
    carbs: '20.01',
    fibre: '1.80',
    sugars: '0.85',
    saturatedFat: '0.03',
    salt: '0.01',
    source: FDC,
  },
  {
    name: 'Морква сира',
    group: 'VEGETABLES',
    kcal: '41.00',
    protein: '0.93',
    fat: '0.24',
    carbs: '9.58',
    fibre: '2.80',
    sugars: '4.74',
    saturatedFat: '0.04',
    salt: '0.17',
    source: FDC,
    portions: [{ label: 'морквина середня', grams: '60.00' }],
  },
  {
    name: 'Буряк варений',
    group: 'VEGETABLES',
    kcal: '44.00',
    protein: '1.68',
    fat: '0.18',
    carbs: '9.96',
    fibre: '2.00',
    sugars: '7.96',
    saturatedFat: '0.03',
    salt: '0.19',
    source: FDC,
  },
  {
    name: 'Капуста білоголова сира',
    group: 'VEGETABLES',
    kcal: '25.00',
    protein: '1.28',
    fat: '0.10',
    carbs: '5.80',
    fibre: '2.50',
    sugars: '3.20',
    saturatedFat: '0.03',
    salt: '0.05',
    source: FDC,
  },
  {
    // FoodData Central reports 4.28 g carbohydrate against 2.9 g fibre and
    // 1.78 g sugars, which sum past it — different analytical methods again, as
    // with milk. Sugars are trimmed so the two subsets fit inside the whole.
    name: 'Квашена капуста',
    group: 'VEGETABLES',
    kcal: '19.00',
    protein: '0.91',
    fat: '0.14',
    carbs: '4.28',
    fibre: '2.90',
    sugars: '1.38',
    saturatedFat: '0.03',
    salt: '1.68',
    source: FDC,
  },
  {
    name: 'Цибуля ріпчаста',
    group: 'VEGETABLES',
    kcal: '40.00',
    protein: '1.10',
    fat: '0.10',
    carbs: '9.34',
    fibre: '1.70',
    sugars: '4.24',
    saturatedFat: '0.04',
    salt: '0.01',
    source: FDC,
  },
  {
    name: 'Помідор',
    group: 'VEGETABLES',
    kcal: '18.00',
    protein: '0.88',
    fat: '0.20',
    carbs: '3.89',
    fibre: '1.20',
    sugars: '2.63',
    saturatedFat: '0.03',
    salt: '0.01',
    source: FDC,
    portions: [{ label: 'помідор середній', grams: '120.00' }],
  },
  {
    name: 'Огірок',
    group: 'VEGETABLES',
    kcal: '15.00',
    protein: '0.65',
    fat: '0.11',
    carbs: '3.63',
    fibre: '0.50',
    sugars: '1.67',
    saturatedFat: '0.04',
    salt: '0.01',
    source: FDC,
  },
  {
    name: 'Броколі сира',
    group: 'VEGETABLES',
    kcal: '34.00',
    protein: '2.82',
    fat: '0.37',
    carbs: '6.64',
    fibre: '2.60',
    sugars: '1.70',
    saturatedFat: '0.04',
    salt: '0.08',
    source: FDC,
  },
  {
    name: 'Гарбуз сирий',
    group: 'VEGETABLES',
    kcal: '26.00',
    protein: '1.00',
    fat: '0.10',
    carbs: '6.50',
    fibre: '0.50',
    sugars: '2.76',
    saturatedFat: '0.05',
    salt: '0.00',
    source: FDC,
  },

  // ── Фрукти та ягоди ─────────────────────────────────────────────────────
  {
    name: 'Яблуко',
    group: 'FRUIT',
    kcal: '52.00',
    protein: '0.26',
    fat: '0.17',
    carbs: '13.81',
    fibre: '2.40',
    sugars: '10.39',
    saturatedFat: '0.03',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'яблуко середнє', grams: '180.00' }],
  },
  {
    name: 'Банан',
    group: 'FRUIT',
    kcal: '89.00',
    protein: '1.09',
    fat: '0.33',
    carbs: '22.84',
    fibre: '2.60',
    sugars: '12.23',
    saturatedFat: '0.11',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'банан середній', grams: '118.00' }],
  },
  {
    name: 'Груша',
    group: 'FRUIT',
    kcal: '57.00',
    protein: '0.36',
    fat: '0.14',
    carbs: '15.23',
    fibre: '3.10',
    sugars: '9.75',
    saturatedFat: '0.02',
    salt: '0.00',
    source: FDC,
  },
  {
    name: 'Слива',
    group: 'FRUIT',
    kcal: '46.00',
    protein: '0.70',
    fat: '0.28',
    carbs: '11.42',
    fibre: '1.40',
    sugars: '9.92',
    saturatedFat: '0.02',
    salt: '0.00',
    source: FDC,
  },
  {
    name: 'Полуниця',
    group: 'FRUIT',
    kcal: '32.00',
    protein: '0.67',
    fat: '0.30',
    carbs: '7.68',
    fibre: '2.00',
    sugars: '4.89',
    saturatedFat: '0.02',
    salt: '0.00',
    source: FDC,
  },
  {
    name: 'Чорниця',
    group: 'FRUIT',
    kcal: '57.00',
    protein: '0.74',
    fat: '0.33',
    carbs: '14.49',
    fibre: '2.40',
    sugars: '9.96',
    saturatedFat: '0.03',
    salt: '0.00',
    source: FDC,
  },
  {
    name: 'Вишня',
    group: 'FRUIT',
    kcal: '50.00',
    protein: '1.00',
    fat: '0.30',
    carbs: '12.18',
    fibre: '1.60',
    sugars: '8.49',
    saturatedFat: '0.07',
    salt: '0.01',
    source: FDC,
  },
  {
    name: 'Смородина чорна',
    group: 'FRUIT',
    kcal: '63.00',
    protein: '1.40',
    fat: '0.41',
    carbs: '15.38',
    fibre: '4.30',
    sugars: '7.37',
    saturatedFat: '0.03',
    salt: '0.01',
    source: FDC,
  },

  // ── Горіхи та насіння ───────────────────────────────────────────────────
  {
    name: 'Волоські горіхи',
    group: 'NUTS_SEEDS',
    kcal: '654.00',
    protein: '15.23',
    fat: '65.21',
    carbs: '13.71',
    fibre: '6.70',
    sugars: '2.61',
    saturatedFat: '6.13',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'жменя', grams: '30.00' }],
  },
  {
    name: 'Мигдаль',
    group: 'NUTS_SEEDS',
    kcal: '579.00',
    protein: '21.15',
    fat: '49.93',
    carbs: '21.55',
    fibre: '12.50',
    sugars: '4.35',
    saturatedFat: '3.80',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'жменя', grams: '30.00' }],
  },
  {
    name: 'Соняшникове насіння',
    group: 'NUTS_SEEDS',
    kcal: '584.00',
    protein: '20.78',
    fat: '51.46',
    carbs: '20.00',
    fibre: '8.60',
    sugars: '2.62',
    saturatedFat: '4.46',
    salt: '0.02',
    source: FDC,
  },
  {
    name: 'Гарбузове насіння',
    group: 'NUTS_SEEDS',
    kcal: '559.00',
    protein: '30.23',
    fat: '49.05',
    carbs: '10.71',
    fibre: '6.00',
    sugars: '1.40',
    saturatedFat: '8.67',
    salt: '0.02',
    source: FDC,
  },

  // ── Бобові ──────────────────────────────────────────────────────────────
  {
    name: 'Квасоля варена',
    group: 'LEGUMES',
    kcal: '127.00',
    protein: '8.67',
    fat: '0.50',
    carbs: '22.80',
    fibre: '6.40',
    sugars: '0.32',
    saturatedFat: '0.13',
    salt: '0.00',
    source: FDC,
  },
  {
    name: 'Сочевиця варена',
    group: 'LEGUMES',
    kcal: '116.00',
    protein: '9.02',
    fat: '0.38',
    carbs: '20.13',
    fibre: '7.90',
    sugars: '1.80',
    saturatedFat: '0.05',
    salt: '0.01',
    source: FDC,
  },
  {
    name: 'Горох варений',
    group: 'LEGUMES',
    kcal: '118.00',
    protein: '8.34',
    fat: '0.39',
    carbs: '21.10',
    fibre: '8.30',
    sugars: '2.90',
    saturatedFat: '0.05',
    salt: '0.00',
    source: FDC,
  },
  {
    name: 'Нут варений',
    group: 'LEGUMES',
    kcal: '164.00',
    protein: '8.86',
    fat: '2.59',
    carbs: '27.42',
    fibre: '7.60',
    sugars: '4.80',
    saturatedFat: '0.27',
    salt: '0.02',
    source: FDC,
  },

  // ── Олії та жири ────────────────────────────────────────────────────────
  {
    name: 'Соняшникова олія',
    group: 'FATS_OILS',
    kcal: '884.00',
    protein: '0.00',
    fat: '100.00',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '10.30',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'столова ложка', grams: '14.00' }],
  },
  {
    name: 'Оливкова олія',
    group: 'FATS_OILS',
    kcal: '884.00',
    protein: '0.00',
    fat: '100.00',
    carbs: '0.00',
    sugars: '0.00',
    fibre: '0.00',
    saturatedFat: '13.81',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'столова ложка', grams: '14.00' }],
  },

  // ── Хліб та випічка ─────────────────────────────────────────────────────
  {
    name: 'Хліб житній',
    group: 'BAKERY',
    kcal: '259.00',
    protein: '8.50',
    fat: '3.30',
    carbs: '48.30',
    fibre: '5.80',
    sugars: '3.85',
    saturatedFat: '0.63',
    salt: '1.30',
    source: FDC,
    portions: [{ label: 'скибка', grams: '35.00' }],
  },
  {
    name: 'Хліб пшеничний білий',
    group: 'BAKERY',
    kcal: '266.00',
    protein: '7.64',
    fat: '3.29',
    carbs: '50.61',
    fibre: '2.40',
    sugars: '5.34',
    saturatedFat: '0.72',
    salt: '1.20',
    source: FDC,
    portions: [{ label: 'скибка', grams: '30.00' }],
  },

  // ── Солодощі ────────────────────────────────────────────────────────────
  {
    name: 'Мед',
    group: 'SWEETS',
    kcal: '304.00',
    protein: '0.30',
    fat: '0.00',
    carbs: '82.40',
    fibre: '0.20',
    sugars: '82.12',
    saturatedFat: '0.00',
    salt: '0.01',
    source: FDC,
    portions: [{ label: 'чайна ложка', grams: '7.00' }],
  },
  {
    name: 'Цукор білий',
    group: 'SWEETS',
    kcal: '387.00',
    protein: '0.00',
    fat: '0.00',
    carbs: '99.98',
    fibre: '0.00',
    sugars: '99.80',
    saturatedFat: '0.00',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'чайна ложка', grams: '4.00' }],
  },
  {
    name: 'Чорний шоколад 70–85%',
    group: 'SWEETS',
    kcal: '598.00',
    protein: '7.79',
    fat: '42.63',
    carbs: '45.90',
    fibre: '10.90',
    sugars: '23.99',
    saturatedFat: '24.49',
    salt: '0.05',
    source: FDC,
    portions: [{ label: 'квадратик', grams: '10.00' }],
  },

  // ── Напої ───────────────────────────────────────────────────────────────
  {
    name: 'Кава чорна без цукру',
    group: 'BEVERAGES',
    kcal: '1.00',
    protein: '0.12',
    fat: '0.02',
    carbs: '0.00',
    fibre: '0.00',
    sugars: '0.00',
    saturatedFat: '0.00',
    salt: '0.01',
    source: FDC,
    portions: [{ label: 'чашка', grams: '200.00' }],
  },
  {
    name: 'Чай чорний без цукру',
    group: 'BEVERAGES',
    kcal: '1.00',
    protein: '0.00',
    fat: '0.00',
    carbs: '0.30',
    fibre: '0.00',
    sugars: '0.00',
    saturatedFat: '0.00',
    salt: '0.00',
    source: FDC,
    portions: [{ label: 'чашка', grams: '200.00' }],
  },

  // ── Соуси та приправи ───────────────────────────────────────────────────
  {
    name: 'Сіль кухонна',
    group: 'SAUCES',
    kcal: '0.00',
    protein: '0.00',
    fat: '0.00',
    carbs: '0.00',
    fibre: '0.00',
    sugars: '0.00',
    saturatedFat: '0.00',
    salt: '100.00',
    source: FDC,
    portions: [{ label: 'чайна ложка', grams: '6.00' }],
  },
  {
    name: 'Гірчиця столова',
    group: 'SAUCES',
    kcal: '66.00',
    protein: '4.37',
    fat: '3.95',
    carbs: '5.83',
    fibre: '3.30',
    sugars: '0.86',
    saturatedFat: '0.25',
    salt: '2.75',
    source: FDC,
    portions: [{ label: 'чайна ложка', grams: '5.00' }],
  },
  {
    name: 'Томатна паста',
    group: 'SAUCES',
    kcal: '82.00',
    protein: '4.32',
    fat: '0.47',
    carbs: '18.91',
    fibre: '4.10',
    sugars: '12.18',
    saturatedFat: '0.10',
    salt: '0.15',
    source: FDC,
    portions: [{ label: 'столова ложка', grams: '16.00' }],
  },

  // ── Українські страви (наші оцінки) ─────────────────────────────────────
  {
    name: 'Борщ український',
    group: 'OTHER',
    kcal: '52.00',
    protein: '1.60',
    fat: '2.40',
    carbs: '5.80',
    fibre: '1.50',
    sugars: '2.40',
    saturatedFat: '0.90',
    salt: '0.80',
    source: OWN,
    portions: [{ label: 'тарілка', grams: '350.00' }],
  },
  {
    name: 'Вареники з картоплею',
    group: 'OTHER',
    kcal: '182.00',
    protein: '4.60',
    fat: '4.20',
    carbs: '31.00',
    fibre: '1.50',
    sugars: '1.00',
    saturatedFat: '1.40',
    salt: '0.70',
    source: OWN,
    portions: [
      { label: 'вареник', grams: '30.00' },
      { label: 'порція', grams: '250.00' },
    ],
  },
  {
    name: 'Сирники',
    group: 'OTHER',
    kcal: '216.00',
    protein: '13.00',
    fat: '9.00',
    carbs: '21.00',
    fibre: '0.60',
    sugars: '6.00',
    saturatedFat: '4.20',
    salt: '0.50',
    source: OWN,
    portions: [{ label: 'сирник', grams: '60.00' }],
  },
  {
    name: 'Деруни',
    group: 'OTHER',
    kcal: '197.00',
    protein: '3.60',
    fat: '10.50',
    carbs: '21.50',
    fibre: '1.80',
    sugars: '1.20',
    saturatedFat: '1.30',
    salt: '0.60',
    source: OWN,
    portions: [{ label: 'дерун', grams: '45.00' }],
  },
  {
    name: 'Голубці з м’ясом і рисом',
    group: 'OTHER',
    kcal: '119.00',
    protein: '6.30',
    fat: '5.60',
    carbs: '10.80',
    fibre: '1.60',
    sugars: '2.20',
    saturatedFat: '1.90',
    salt: '0.75',
    source: OWN,
    portions: [{ label: 'голубець', grams: '110.00' }],
  },
  {
    name: 'Гречана каша з молоком',
    group: 'OTHER',
    kcal: '105.00',
    protein: '4.10',
    fat: '2.20',
    carbs: '17.60',
    fibre: '2.10',
    sugars: '2.60',
    saturatedFat: '1.00',
    salt: '0.15',
    source: OWN,
    portions: [{ label: 'порція', grams: '250.00' }],
  },
];
